const productList =  [
    {
      id: 1,
      name: "Cement",
      category: "Building Materials",
      price: 100,
      stock: 2500,
    },
    {
      id: 2,
      name: "Hammers",
      category: "Tools",
      price: 144,
      stock: 43,
    },
    {
      id: 3,
      name: "Chisels",
      category: "Equipments",
      price: 28,
      stock: 123,
    },
    {
      id: 4,
      name: "Adhesives and Sealants",
      category: "Consumables",
      price: 85,
      stock: 33,
    },
    {
      id: 5,
      name: "Sandpaper",
      category: "Tools",
      price: 113,
      stock: 11,
    },
    {
      id: 6,
      name: "Drill Bits",
      category: "Tools",
      price: 28,
      stock: 123,
    },
    {
      id: 20,
      name: "Hose Pipe",
      category: "Equipments",
      price: 25,
      stock: 10,
    },
    {
      id: 7,
      name: "Saws",
      category: "Equipments",
      price: 92,
      stock: 323,
    },
    {
      id: 8,
      name: "Lubrication",
      category: "Consumables",
      price: 35,
      stock: 52,
    },
    {
      id: 9,
      name: "Wrenches",
      category: "Tools",
      price: 13,
      stock: 25,
    },

    {
      id: 10,
      name: "Tarps",
      category: "Consumables",
      price: 828,
      stock: 30,
    },
    {
      id: 11,
      name: "Brick",
      category: "Building Materials",
      price: 144,
      stock: 20,
    },
    {
      id: 12,
      name: "Glass",
      category: "Building Materials",
      price: 28,
      stock: 19,
    },
    {
      id: 13,
      name: "Luis glasses",
      category: "Equipment",
      price: 85,
      stock: 30,
    },
    {
      id: 14,
      name: "Safety glasses",
      category: "Consumables",
      price: 113,
      stock: 75,
    },
    {
      id: 15,
      name: "Grinding wheels",
      category: "Consumables",
      price: 28,
      stock: 12,
    },
    {
      id: 16,
      name: "Steel",
      category: "Building Materials",
      price: 25,
      stock: 13,
    },
    {
      id: 17,
      name: "Wood",
      category: "Building Materials",
      price: 92,
      stock: 18,
    },
    {
      id: 18,
      name: "Levels",
      category: "Equipment",
      price: 3500,
      stock: 27,
    },
    {
      id: 19,
      name: "Screwdrivers",
      category: "Equipment",
      price: 13,
      stock: 43,
    },
  ];

  export default productList;